name: Shell Commends

on:
  - push
jobs:
  run-shell-commend:
    runs-on: ubuntu-latest
    steps:
      - name: echo a sting
        run: echo "Hello World!"
      - name: multiline script
        run: |
          node -v
          npm -v
